name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 11
            additional-maven-args: >
              -Pcoveralls,pit
              -DrepoToken=$COVERALLS_REPO_TOKEN
              -DpullRequest=${{ github.event.pull_request.number }}
          - java: 17
            additional-maven-args: >
              -Pjacoco
              sonar:sonar
              -Dsonar.organization=YOUR_ORG
              -Dsonar.projectKey=YOUR_PROJECT_KEY
              -Dsonar.host.url=https://sonarcloud.io

    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn verify ${{ matrix.additional-maven-args }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: tasklist

      - name: Archive PIT report
        if: matrix.java == 11
        uses: actions/upload-artifact@v3
        with:
          name: PIT-report
          path: '**/target/pit-reports'
